---
# foo
image: registry.gitlab.com/aplus-framework/images/base:1

include:
  - template: Security/SAST.gitlab-ci.yml

test:php:
  stage: test
  before_script:
    - composer install
  script:
    - vendor/bin/phpunit --colors=never
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
